import {
  User,
  Content,
  Device,
  Analytics,
  AuditLog,
  SecurityEvent,
  SystemSettings,
  DashboardStats,
  UserRole,
  Playlist,
  PlaylistItem,
  DevicePairingRequest,
  Schedule,
} from './types';

const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: [
    'user:create',
    'user:read',
    'user:update',
    'user:delete',
    'content:create',
    'content:read',
    'content:moderate',
    'content:delete',
    'device:control',
    'device:read',
    'device:reboot',
    'settings:read',
    'settings:update',
    'analytics:read',
    'analytics:export',
    'security:manage',
    'audit:read',
  ],
  admin: [
    'user:read',
    'user:update',
    'content:read',
    'content:moderate',
    'device:read',
    'device:control',
    'settings:read',
    'analytics:read',
    'audit:read',
  ],
  moderator: ['content:read', 'content:moderate', 'device:read', 'analytics:read'],
  device_manager: ['device:read', 'device:control', 'device:reboot'],
  viewer: ['analytics:read', 'device:read', 'content:read'],
};

export const mockUsers: User[] = [
  {
    id: 'user_1',
    email: 'admin@digitalsignage.com',
    name: 'Sarah Johnson',
    role: 'super_admin',
    status: 'active',
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    createdAt: new Date('2024-01-15'),
    permissions: ROLE_PERMISSIONS.super_admin as any,
  },
  {
    id: 'user_2',
    email: 'moderator@digitalsignage.com',
    name: 'Michael Chen',
    role: 'admin',
    status: 'active',
    lastLogin: new Date(Date.now() - 30 * 60 * 1000),
    createdAt: new Date('2024-02-10'),
    permissions: ROLE_PERMISSIONS.admin as any,
  },
  {
    id: 'user_3',
    email: 'content@digitalsignage.com',
    name: 'Emma Davis',
    role: 'moderator',
    status: 'active',
    lastLogin: new Date(Date.now() - 6 * 60 * 60 * 1000),
    createdAt: new Date('2024-03-05'),
    permissions: ROLE_PERMISSIONS.moderator as any,
  },
  {
    id: 'user_4',
    email: 'device@digitalsignage.com',
    name: 'James Wilson',
    role: 'device_manager',
    status: 'active',
    lastLogin: new Date(Date.now() - 12 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-20'),
    permissions: ROLE_PERMISSIONS.device_manager as any,
  },
  {
    id: 'user_5',
    email: 'viewer@digitalsignage.com',
    name: 'Lisa Anderson',
    role: 'viewer',
    status: 'inactive',
    lastLogin: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
    createdAt: new Date('2024-02-01'),
    permissions: ROLE_PERMISSIONS.viewer as any,
  },
];

export const mockContent: Content[] = [
  {
    id: 'content_1',
    title: 'Summer Campaign Banner',
    description: 'Full HD promotional banner for summer collection',
    type: 'image',
    status: 'approved',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    fileSize: 2.5,
    width: 1920,
    height: 1080,
    tags: ['summer', 'promotional', 'banner'],
    category: 'Marketing',
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'content_2',
    title: 'Product Demo Video',
    description: 'New product demonstration and features overview',
    type: 'video',
    status: 'pending_review',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    fileSize: 125.8,
    duration: 45,
    tags: ['product', 'demo', 'video'],
    category: 'Products',
  },
  {
    id: 'content_3',
    title: 'Store Hours Display',
    description: 'Dynamic store hours and contact information',
    type: 'banner',
    status: 'approved',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    fileSize: 0.8,
    tags: ['store-hours', 'info'],
    category: 'Information',
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'content_4',
    title: 'Breaking News Ticker',
    description: 'Scrolling news ticker for lobby displays',
    type: 'news_ticker',
    status: 'approved',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    fileSize: 0.2,
    tags: ['news', 'ticker', 'scrolling'],
    category: 'News',
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'content_5',
    title: 'Q4 Sales Presentation',
    description: 'Quarterly sales figures and projections',
    type: 'html',
    status: 'draft',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 30 * 60 * 1000),
    fileSize: 4.5,
    tags: ['sales', 'q4', 'presentation'],
    category: 'Reports',
  },
  {
    id: 'content_6',
    title: 'Restaurant Menu Board',
    description: 'Digital menu with pricing and categories',
    type: 'menu',
    status: 'pending_review',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    fileSize: 1.2,
    width: 1920,
    height: 1080,
    tags: ['menu', 'restaurant', 'food'],
    category: 'Menu',
  },
  {
    id: 'content_7',
    title: 'Welcome Video Loop',
    description: '15-second ambient welcome video for reception',
    type: 'video',
    status: 'approved',
    uploadedBy: 'user_2',
    uploadedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    fileSize: 48.3,
    duration: 15,
    width: 3840,
    height: 2160,
    tags: ['welcome', 'ambient', 'loop'],
    category: 'Branding',
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000),
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: 'playlist_1',
    name: 'Lobby Welcome Loop',
    description: 'Default lobby display playlist cycling through branding and info',
    items: [
      { id: 'pli_1', contentId: 'content_1', order: 0, duration: 10 },
      { id: 'pli_2', contentId: 'content_7', order: 1, duration: 15 },
      { id: 'pli_3', contentId: 'content_3', order: 2, duration: 8 },
      { id: 'pli_4', contentId: 'content_4', order: 3, duration: 12 },
    ],
    loop: true,
    totalDuration: 45,
    status: 'active',
    createdBy: 'user_1',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    assignedDevices: ['device_1', 'device_2'],
  },
  {
    id: 'playlist_2',
    name: 'Product Showcase',
    description: 'Highlights new products and demo videos for store displays',
    items: [
      { id: 'pli_5', contentId: 'content_2', order: 0, duration: 45 },
      { id: 'pli_6', contentId: 'content_1', order: 1, duration: 10 },
    ],
    loop: true,
    totalDuration: 55,
    status: 'active',
    createdBy: 'user_2',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    assignedDevices: ['device_5'],
  },
  {
    id: 'playlist_3',
    name: 'Restaurant Menu Board',
    description: 'Food menu display for dining area screens',
    items: [
      { id: 'pli_7', contentId: 'content_6', order: 0, duration: 30 },
      { id: 'pli_8', contentId: 'content_4', order: 1, duration: 10 },
    ],
    loop: true,
    totalDuration: 40,
    status: 'draft',
    createdBy: 'user_1',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    assignedDevices: [],
  },
];

export const mockPairingRequests: DevicePairingRequest[] = [
  {
    id: 'pair_1',
    pairingCode: 'DSP-4829',
    deviceName: 'Meeting Room A Display',
    deviceType: 'android_tv',
    macAddress: 'A4:C3:F0:85:B2:11',
    requestedAt: new Date(Date.now() - 10 * 60 * 1000),
    status: 'pending',
  },
  {
    id: 'pair_2',
    pairingCode: 'DSP-7731',
    deviceName: 'Cafeteria Display Left',
    deviceType: 'display',
    macAddress: 'B8:27:EB:4F:2A:99',
    requestedAt: new Date(Date.now() - 35 * 60 * 1000),
    status: 'pending',
  },
  {
    id: 'pair_3',
    pairingCode: 'DSP-1142',
    deviceName: 'Reception Tablet',
    deviceType: 'tablet',
    macAddress: 'DC:A6:32:00:3F:C2',
    requestedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: 'approved',
    approvedBy: 'user_1',
    approvedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: 'sched_1',
    name: 'Weekday Lobby Morning',
    playlistId: 'playlist_1',
    deviceIds: ['device_1', 'device_2'],
    days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    timeSlot: { start: '08:00', end: '12:00' },
    startDate: '2024-01-01',
    isActive: true,
    priority: 1,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sched_2',
    name: 'Product Showcase Afternoons',
    playlistId: 'playlist_2',
    deviceIds: ['device_5'],
    days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    timeSlot: { start: '12:00', end: '20:00' },
    isActive: true,
    priority: 2,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'sched_3',
    name: 'Weekend Special',
    playlistId: 'playlist_1',
    deviceIds: ['device_1'],
    days: ['saturday', 'sunday'],
    timeSlot: { start: '10:00', end: '18:00' },
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    isActive: false,
    priority: 3,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
];

export const mockDevices: Device[] = [
  {
    id: 'device_1',
    name: 'Main Lobby Display',
    type: 'display',
    status: 'online',
    location: 'New York - Headquarters',
    ipAddress: '192.168.1.101',
    lastHeartbeat: new Date(Date.now() - 30 * 1000), // 30 seconds ago
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1', 'content_3'],
    uptime: 99.8,
    errorCount: 2,
    temperature: 42,
  },
  {
    id: 'device_2',
    name: 'East Wing Display',
    type: 'display',
    status: 'online',
    location: 'New York - Headquarters',
    ipAddress: '192.168.1.102',
    lastHeartbeat: new Date(Date.now() - 45 * 1000),
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1'],
    uptime: 98.5,
    errorCount: 5,
    temperature: 38,
  },
  {
    id: 'device_3',
    name: 'Chicago Branch Display',
    type: 'display',
    status: 'offline',
    location: 'Chicago - Branch Office',
    ipAddress: '192.168.2.101',
    lastHeartbeat: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    osVersion: 'Android 12',
    softwareVersion: '2.4.0',
    assignedContent: ['content_3'],
    uptime: 0,
    errorCount: 12,
  },
  {
    id: 'device_4',
    name: 'Server Node 01',
    type: 'server',
    status: 'online',
    location: 'Cloud Infrastructure',
    ipAddress: '10.0.1.50',
    lastHeartbeat: new Date(Date.now() - 5 * 1000),
    osVersion: 'Ubuntu 22.04 LTS',
    softwareVersion: '2.4.1',
    uptime: 99.99,
    errorCount: 0,
    temperature: 35,
  },
  {
    id: 'device_5',
    name: 'Los Angeles Store Display',
    type: 'display',
    status: 'online',
    location: 'Los Angeles - Store',
    ipAddress: '192.168.3.101',
    lastHeartbeat: new Date(Date.now() - 2 * 60 * 1000),
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1', 'content_3'],
    uptime: 97.2,
    errorCount: 8,
    temperature: 45,
  },
];

export const mockAnalytics: Analytics[] = Array.from({ length: 30 }, (_, i) => {
  const daysAgo = 29 - i;
  return {
    date: new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000),
    activeDevices: Math.floor(Math.random() * 3) + 4,
    totalPlaybacks: Math.floor(Math.random() * 500) + 300,
    totalViews: Math.floor(Math.random() * 2000) + 1000,
    averagePlayDuration: Math.floor(Math.random() * 120) + 30,
    errorRate: Math.random() * 5,
    contentApprovals: Math.floor(Math.random() * 5),
    newUsers: Math.floor(Math.random() * 3),
  };
});

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit_1',
    userId: 'user_1',
    action: 'UPDATE',
    resource: 'User',
    resourceId: 'user_3',
    changes: { role: 'viewer', newRole: 'moderator' },
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'audit_2',
    userId: 'user_1',
    action: 'DELETE',
    resource: 'Content',
    resourceId: 'content_4',
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'audit_3',
    userId: 'user_2',
    action: 'REBOOT',
    resource: 'Device',
    resourceId: 'device_3',
    ipAddress: '203.0.113.46',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'audit_4',
    userId: 'user_1',
    action: 'UPDATE',
    resource: 'Settings',
    resourceId: 'system_settings',
    changes: { sessionTimeout: 30, newSessionTimeout: 60 },
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
];

export const mockSecurityEvents: SecurityEvent[] = [
  {
    id: 'sec_1',
    type: 'login_attempt',
    severity: 'low',
    userId: 'user_1',
    description: 'Successful login from IP 203.0.113.45',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    resolved: true,
  },
  {
    id: 'sec_2',
    type: 'permission_change',
    severity: 'medium',
    userId: 'user_1',
    description: 'User permissions modified for user_3',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    resolved: true,
  },
  {
    id: 'sec_3',
    type: 'data_access',
    severity: 'high',
    description: 'Multiple failed API authentication attempts detected',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    resolved: false,
  },
  {
    id: 'sec_4',
    type: 'config_change',
    severity: 'high',
    userId: 'user_1',
    description: 'System settings configuration updated',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    resolved: true,
  },
];

export const mockSystemSettings: SystemSettings = {
  appName: 'Digital Signage Pro',
  maintenanceMode: false,
  maxUploadSize: 500,
  sessionTimeout: 60,
  passwordPolicy: {
    minLength: 12,
    requireUppercase: true,
    requireNumbers: true,
    requireSpecialChars: true,
  },
  twoFactorAuth: true,
  ipWhitelist: ['203.0.113.0/24', '198.51.100.0/24'],
  contentRetentionDays: 365,
  auditLogRetentionDays: 90,
};

export const mockDashboardStats: DashboardStats = {
  totalUsers: 24,
  activeUsers: 18,
  totalDevices: 12,
  onlineDevices: 10,
  pendingContent: 3,
  approvedContent: 42,
  systemHealth: 94,
  securityScore: 87,
};
