import {
  User,
  Content,
  Device,
  Analytics,
  AuditLog,
  SecurityEvent,
  SystemSettings,
  DashboardStats,
  UserRole,
} from './types';

const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: [
    'user:create',
    'user:read',
    'user:update',
    'user:delete',
    'content:create',
    'content:read',
    'content:moderate',
    'content:delete',
    'device:control',
    'device:read',
    'device:reboot',
    'settings:read',
    'settings:update',
    'analytics:read',
    'analytics:export',
    'security:manage',
    'audit:read',
  ],
  admin: [
    'user:read',
    'user:update',
    'content:read',
    'content:moderate',
    'device:read',
    'device:control',
    'settings:read',
    'analytics:read',
    'audit:read',
  ],
  moderator: ['content:read', 'content:moderate', 'device:read', 'analytics:read'],
  device_manager: ['device:read', 'device:control', 'device:reboot'],
  viewer: ['analytics:read', 'device:read', 'content:read'],
};

export const mockUsers: User[] = [
  {
    id: 'user_1',
    email: 'admin@digitalsignage.com',
    name: 'Sarah Johnson',
    role: 'super_admin',
    status: 'active',
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    createdAt: new Date('2024-01-15'),
    permissions: ROLE_PERMISSIONS.super_admin as any,
  },
  {
    id: 'user_2',
    email: 'moderator@digitalsignage.com',
    name: 'Michael Chen',
    role: 'admin',
    status: 'active',
    lastLogin: new Date(Date.now() - 30 * 60 * 1000),
    createdAt: new Date('2024-02-10'),
    permissions: ROLE_PERMISSIONS.admin as any,
  },
  {
    id: 'user_3',
    email: 'content@digitalsignage.com',
    name: 'Emma Davis',
    role: 'moderator',
    status: 'active',
    lastLogin: new Date(Date.now() - 6 * 60 * 60 * 1000),
    createdAt: new Date('2024-03-05'),
    permissions: ROLE_PERMISSIONS.moderator as any,
  },
  {
    id: 'user_4',
    email: 'device@digitalsignage.com',
    name: 'James Wilson',
    role: 'device_manager',
    status: 'active',
    lastLogin: new Date(Date.now() - 12 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-20'),
    permissions: ROLE_PERMISSIONS.device_manager as any,
  },
  {
    id: 'user_5',
    email: 'viewer@digitalsignage.com',
    name: 'Lisa Anderson',
    role: 'viewer',
    status: 'inactive',
    lastLogin: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
    createdAt: new Date('2024-02-01'),
    permissions: ROLE_PERMISSIONS.viewer as any,
  },
];

export const mockContent: Content[] = [
  {
    id: 'content_1',
    title: 'Summer Campaign Banner',
    description: 'Full HD promotional banner for summer collection',
    type: 'image',
    status: 'approved',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    fileSize: 2.5,
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'content_2',
    title: 'Product Demo Video',
    description: 'New product demonstration and features',
    type: 'video',
    status: 'pending_review',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    fileSize: 125.8,
    duration: 45,
  },
  {
    id: 'content_3',
    title: 'Store Hours Template',
    description: 'Dynamic store hours display',
    type: 'template',
    status: 'approved',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    fileSize: 0.8,
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'content_4',
    title: 'Inappropriate Content Test',
    description: 'Test image with potential policy violation',
    type: 'image',
    status: 'rejected',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    fileSize: 3.2,
    reviewedBy: 'user_1',
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rejectionReason: 'Content violates brand guidelines',
  },
  {
    id: 'content_5',
    title: 'Q4 Sales Presentation',
    description: 'Quarterly sales figures and projections',
    type: 'html',
    status: 'draft',
    uploadedBy: 'user_3',
    uploadedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    modifiedAt: new Date(Date.now() - 30 * 60 * 1000),
    fileSize: 4.5,
  },
];

export const mockDevices: Device[] = [
  {
    id: 'device_1',
    name: 'Main Lobby Display',
    type: 'display',
    status: 'online',
    location: 'New York - Headquarters',
    ipAddress: '192.168.1.101',
    lastHeartbeat: new Date(Date.now() - 30 * 1000), // 30 seconds ago
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1', 'content_3'],
    uptime: 99.8,
    errorCount: 2,
    temperature: 42,
  },
  {
    id: 'device_2',
    name: 'East Wing Display',
    type: 'display',
    status: 'online',
    location: 'New York - Headquarters',
    ipAddress: '192.168.1.102',
    lastHeartbeat: new Date(Date.now() - 45 * 1000),
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1'],
    uptime: 98.5,
    errorCount: 5,
    temperature: 38,
  },
  {
    id: 'device_3',
    name: 'Chicago Branch Display',
    type: 'display',
    status: 'offline',
    location: 'Chicago - Branch Office',
    ipAddress: '192.168.2.101',
    lastHeartbeat: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    osVersion: 'Android 12',
    softwareVersion: '2.4.0',
    assignedContent: ['content_3'],
    uptime: 0,
    errorCount: 12,
  },
  {
    id: 'device_4',
    name: 'Server Node 01',
    type: 'server',
    status: 'online',
    location: 'Cloud Infrastructure',
    ipAddress: '10.0.1.50',
    lastHeartbeat: new Date(Date.now() - 5 * 1000),
    osVersion: 'Ubuntu 22.04 LTS',
    softwareVersion: '2.4.1',
    uptime: 99.99,
    errorCount: 0,
    temperature: 35,
  },
  {
    id: 'device_5',
    name: 'Los Angeles Store Display',
    type: 'display',
    status: 'online',
    location: 'Los Angeles - Store',
    ipAddress: '192.168.3.101',
    lastHeartbeat: new Date(Date.now() - 2 * 60 * 1000),
    osVersion: 'Android 13',
    softwareVersion: '2.4.1',
    assignedContent: ['content_1', 'content_3'],
    uptime: 97.2,
    errorCount: 8,
    temperature: 45,
  },
];

export const mockAnalytics: Analytics[] = Array.from({ length: 30 }, (_, i) => {
  const daysAgo = 29 - i;
  return {
    date: new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000),
    activeDevices: Math.floor(Math.random() * 3) + 4,
    totalPlaybacks: Math.floor(Math.random() * 500) + 300,
    totalViews: Math.floor(Math.random() * 2000) + 1000,
    averagePlayDuration: Math.floor(Math.random() * 120) + 30,
    errorRate: Math.random() * 5,
    contentApprovals: Math.floor(Math.random() * 5),
    newUsers: Math.floor(Math.random() * 3),
  };
});

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit_1',
    userId: 'user_1',
    action: 'UPDATE',
    resource: 'User',
    resourceId: 'user_3',
    changes: { role: 'viewer', newRole: 'moderator' },
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'audit_2',
    userId: 'user_1',
    action: 'DELETE',
    resource: 'Content',
    resourceId: 'content_4',
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'audit_3',
    userId: 'user_2',
    action: 'REBOOT',
    resource: 'Device',
    resourceId: 'device_3',
    ipAddress: '203.0.113.46',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'audit_4',
    userId: 'user_1',
    action: 'UPDATE',
    resource: 'Settings',
    resourceId: 'system_settings',
    changes: { sessionTimeout: 30, newSessionTimeout: 60 },
    ipAddress: '203.0.113.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
];

export const mockSecurityEvents: SecurityEvent[] = [
  {
    id: 'sec_1',
    type: 'login_attempt',
    severity: 'low',
    userId: 'user_1',
    description: 'Successful login from IP 203.0.113.45',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    resolved: true,
  },
  {
    id: 'sec_2',
    type: 'permission_change',
    severity: 'medium',
    userId: 'user_1',
    description: 'User permissions modified for user_3',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    resolved: true,
  },
  {
    id: 'sec_3',
    type: 'data_access',
    severity: 'high',
    description: 'Multiple failed API authentication attempts detected',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    resolved: false,
  },
  {
    id: 'sec_4',
    type: 'config_change',
    severity: 'high',
    userId: 'user_1',
    description: 'System settings configuration updated',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    resolved: true,
  },
];

export const mockSystemSettings: SystemSettings = {
  appName: 'Digital Signage Pro',
  maintenanceMode: false,
  maxUploadSize: 500,
  sessionTimeout: 60,
  passwordPolicy: {
    minLength: 12,
    requireUppercase: true,
    requireNumbers: true,
    requireSpecialChars: true,
  },
  twoFactorAuth: true,
  ipWhitelist: ['203.0.113.0/24', '198.51.100.0/24'],
  contentRetentionDays: 365,
  auditLogRetentionDays: 90,
};

export const mockDashboardStats: DashboardStats = {
  totalUsers: 24,
  activeUsers: 18,
  totalDevices: 12,
  onlineDevices: 10,
  pendingContent: 3,
  approvedContent: 42,
  systemHealth: 94,
  securityScore: 87,
};
